name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - sklearn
  - pip
  - pip:
    - cvxpy
    - gcvspline
    - rampy
    - lmfit
    - emcee
